name: Build on new tag

on:
  push:
    tags:
      - '*'

jobs:
  Build-And-Push-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set env
        run: echo "TAG_NAME=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        id: buid-push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          push: true
          tags: artvit/orangepi-health-check:latest,artvit/orangepi-health-check:${{ env.TAG_NAME }}
